exports.seed = (knex, Promise) => {
    return knex.raw('DELETE FROM deckorderfil;')
      .then(() => {
        const orders = [
            {
              order_id: '1',
              ordnbr: 'D1234',
              status: 'Upcoming',
              pm_assigned: 'Neal W.',
              origin: 'New Orleans, LA',
              destination: 'Monaca, PA',
              est_start_date: '2020-11-15',
              origin_desc: 'Nashville Wharf',
              destination_desc: 'LNG Plant',
              ord_notes: 'Current start date may change depending on weather.',
              customer: 'Mammoet',
              customer_nm: 'Joey Ardoin',
              customer_phone: '5053332222',
              customer_email: 'joey@mammoet.com',
              customer_notes: 'add customer notes here',
              vendor: 'LA Carriers',
              vendor_nm: 'Tommy Plaisance',
              vendor_phone: '5053339999',
              vendor_email: 'tommy@lacarriers.com',
              vendor_notes: 'add vendor notes here',
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            },
            {
              order_id: '2',
              ordnbr: 'D2345',
              status: 'Upcoming',
              pm_assigned: 'Andrew D.',
              origin: 'Houston, TX',
              destination: 'Houston, TX',
              est_start_date: '2020-12-1',
              origin_desc: 'City Docks',
              destination_desc: 'Barbours Cut',
              ord_notes: 'Day rate job, multiple back and forths.',
              customer: 'Mammoet',
              customer_nm: 'Chad Lowry',
              customer_phone: '4043330000',
              customer_email: 'chad@mammoet.com',
              customer_notes: 'add customer notes here',
              vendor: 'Marquette',
              vendor_nm: 'Tim Dietz',
              vendor_phone: '3934440000',
              vendor_email: 'tdietz@marquette.com',
              vendor_notes: 'add vendor notes here',
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            },
            {
              order_id: '3',
              ordnbr: 'D3456',
              status: 'Active',
              pm_assigned: 'John W.',
              origin: 'Iuka, MS',
              destination: 'Theodore, AL',
              est_start_date: '2020-10-15',
              origin_desc: 'RORO Facility',
              destination_desc: 'Core Industries',
              ord_notes: 'Technip day rate job',
              customer: 'Technip',
              customer_nm: 'Billy Bob',
              customer_phone: '4042220000',
              customer_email: 'bbob@technip.com',
              customer_notes: 'add customer notes here',
              vendor: 'D&S Towing',
              vendor_nm: 'Hal Domingo',
              vendor_phone: '3830003939',
              vendor_email: 'hdomingo@aol.com',
              vendor_notes: 'add vendor notes here',
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            },
            {
              order_id: '4',
              ordnbr: 'D4567',
              status: 'Active',
              pm_assigned: 'Andrew D.',
              origin: 'Monaca, PA',
              destination: 'Geismar, LA',
              est_start_date: '2020-10-05',
              origin_desc: 'Bechtel LNG Plant',
              destination_desc: 'RORO Location MM-185',
              ord_notes: 'Bechtel trip, 1 of 18 (17 to go)',
              customer: 'Bechtel',
              customer_nm: 'Joe Horn',
              customer_phone: '4940002222',
              customer_email: 'cellphone@saints.com',
              customer_notes: 'add customer notes here',
              vendor: 'Marquette',
              vendor_nm: 'Tim Dietz',
              vendor_phone: '3839484948',
              vendor_email: 'tdietz@marquette.com',
              vendor_notes: 'add vendor notes here',
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            },
            {
              order_id: '5',
              ordnbr: 'D5678',
              status: 'Completed',
              pm_assigned: 'Neal W.',
              origin: 'Baytown, TX',
              destination: 'Port Arthur, TX',
              est_start_date: '2020-03-20',
              origin_desc: 'Baytown General Yard',
              destination_desc: 'Deugro Laydown Yard',
              ord_notes: 'Job was a success.  Made $60k profit.',
              customer: 'Deugro',
              customer_nm: 'John Daly',
              customer_phone: '4940292020',
              customer_email: 'beerdrinker12@aol.com',
              customer_notes: 'add customer notes here',
              vendor: 'Crosby Tugs',
              vendor_nm: 'John Crosby',
              vendor_phone: '8192930292',
              vendor_email: 'jcrosby@crosbytugs.com',
              vendor_notes: 'add vendor notes here',
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            },
            {
              order_id: '6',
              ordnbr: 'D6789',
              status: 'Completed',
              pm_assigned: 'John W.',
              origin: 'Houston, TX',
              destination: 'Cameron, LA',
              est_start_date: '2020-06-05',
              origin_desc: 'City Docks',
              destination_desc: 'Venture Global Yard',
              ord_notes: 'For Venture Global LNG.  This job led to knock on work.',
              customer: 'Gulf Coast Prestress',
              customer_nm: 'John Wayne Bobbitt',
              customer_phone: '8585859555',
              customer_email: 'whoops@aol.com',
              customer_notes: 'add customer notes here',
              vendor: 'LA Carriers',
              vendor_nm: 'Tommy Plaisance',
              vendor_phone: '8289283928',
              vendor_email: 'tommy@lacarriers.com',
              vendor_notes: 'add vendor notes here',
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            }
           ];
        return knex('deckorderfil').insert(orders)
      });
};