exports.seed = (knex, Promise) => {
    return knex.raw('DELETE FROM deckvsllogs;')
      .then(() => {
        const logs = [
          {
            log_id: 1,
            ordnbr: 'D3',
            asset_name: 'CBC Savannah',
            log_dttm: new Date(),
            start_fuel: 40000,
            fuel_burn: 1200,
            start_lube: 600,
            lube_burn: 5,
            latitude: 90.000000,
            longitude: -80.000000,
            direction: 'N',
            speed: 7,
            speed_uom: 'kts',
            miles_made: 120,
            dest_desc: 'Monaca, PA',
            dest_eta: '12/17/86',
            dest_mtg: 892,
            notes: 'making good time, should be arriving ahead of schedule',
            location: 'LM-100',
            status: 'Mobilizing',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 2,
            ordnbr: 'D3',
            asset_name: 'Capt. Chase',
            log_dttm: new Date(),
            start_fuel: 40000,
            fuel_burn: 1200,
            start_lube: 600,
            lube_burn: 5,
            latitude: 90.000000,
            longitude: -80.000000,
            direction: 'N',
            speed: 7,
            speed_uom: 'kts',
            miles_made: 120,
            dest_desc: 'Monaca, PA',
            dest_eta: '12/17/86',
            dest_mtg: 892,
            notes: 'making good time, should be arriving ahead of schedule',
            location: 'LM-100',
            status: 'Mobilizing',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 3,
            ordnbr: 'D3',
            asset_name: 'Capt. Chase',
            log_dttm: new Date(),
            start_fuel: 40000,
            fuel_burn: 1200,
            start_lube: 600,
            lube_burn: 5,
            latitude: 90.000000,
            longitude: -80.000000,
            direction: 'N',
            speed: 7,
            speed_uom: 'kts',
            miles_made: 120,
            dest_desc: 'Monaca, PA',
            dest_eta: '12/17/86',
            dest_mtg: 892,
            notes: 'next log',
            location: 'LM-100',
            status: 'Mobilizing',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 4,
            ordnbr: 'D3',
            asset_name: 'Trey Paul',
            log_dttm: new Date(),
            start_fuel: 40000,
            fuel_burn: 1200,
            start_lube: 600,
            lube_burn: 5,
            latitude: 90.000000,
            longitude: -80.000000,
            direction: 'N',
            speed: 7,
            speed_uom: 'kts',
            miles_made: 120,
            dest_desc: 'Monaca, PA',
            dest_eta: '12/17/86',
            dest_mtg: 892,
            notes: 'next log',
            location: 'LM-100',
            status: 'Mobilizing',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          }];
        return knex('deckvsllogs').insert(logs)
      });
};