exports.seed = (knex, Promise) => {
    return knex.raw('DELETE FROM deckvsllogs;')
      .then(() => {
        const logs = [
          {
            log_id: 1,
            order_id: 2,
            asset_id: 1,
            log_dttm: new Date(),
            fuel_burn: 1200,
            lube_burn: 5,
            latitude: '29.966832',
            longitude: '-90.148765', 
            direction: 'N',
            speed: 7,
            miles_made: 120,
            miles_to_go: 70,
            eta: new Date(),
            notes: 'log 1',
            asset_location: 'LM-100',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 2,
            order_id: 2,
            asset_id: 1,
            log_dttm: new Date(),
            fuel_burn: 1100,
            lube_burn: 0,
            latitude: '29.966832',
            longitude: '-90.148765', 
            direction: 'N',
            speed: 5.6,
            miles_made: 160,
            miles_to_go: 90,
            eta: new Date(),
            notes: 'log 2',
            asset_location: 'LM-100',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 3,
            order_id: 3,
            asset_id: 4,
            log_dttm: new Date(),
            fuel_burn: 1100,
            lube_burn: 0,
            latitude: '29.966832',
            longitude: '-90.148765', 
            direction: 'N',
            speed: 5.6,
            miles_made: 160,
            miles_to_go: 90,
            eta: new Date(),
            notes: 'log 2',
            asset_location: 'LM-100',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 4,
            order_id: 3,
            asset_id: 5,
            log_dttm: new Date(),
            fuel_burn: 1100,
            lube_burn: 0,
            latitude: '29.966832',
            longitude: '-90.148765', 
            direction: 'N',
            speed: 5.6,
            miles_made: 160,
            miles_to_go: 90,
            eta: new Date(),
            notes: 'log 2',
            asset_location: 'LM-100',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 5,
            order_id: 3,
            asset_id: 5,
            log_dttm: new Date(),
            fuel_burn: 1100,
            lube_burn: 0,
            latitude: '29.966832',
            longitude: '-90.148765', 
            direction: 'N',
            speed: 5.6,
            miles_made: 160,
            miles_to_go: 90,
            eta: new Date(),
            notes: 'log 2',
            asset_location: 'LM-100',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          },
          {
            log_id: 6,
            order_id: 2,
            asset_id: 1,
            log_dttm: new Date(),
            fuel_burn: 1200,
            lube_burn: 5,
            latitude: '29.966832',
            longitude: '-90.148765', 
            direction: 'N',
            speed: 70,
            miles_made: 120,
            miles_to_go: 70,
            eta: new Date(),
            notes: 'log 1',
            asset_location: 'LM-800',
            created_by: 'Neal White',
            last_modified_by: 'Neal White',
            created_dttm: new Date(),
            modified_dttm: new Date()
          }
        
        ];
        return knex('deckvsllogs').insert(logs)
      });
};