exports.seed = (knex, Promise) => {
    return knex.raw('DELETE FROM deckassetfil;')
      .then(() => {
        const assets = [
            {
              asset_id: '1',
              order_id: '2',
              asset_status: 'Active',
              tow_group: '1',
              asset_type: 'tug',
              asset_name: 'M/V Trident',
              asset_start: '2020-11-15',
              asset_stop: '2020-11-28',
              vendor_name: 'marquette',
              start_fuel: '40000',
              stop_fuel: 0,
              start_lube: '200',
              stop_lube: 0,
              created_by: 'Neal White',
              last_modified_by: 'Neal White',
              created_dttm: new Date(),
              modified_dttm: new Date()
            },
            {
              
                asset_id: '2',
                order_id: '2',
                asset_status: 'Active',
                tow_group: '2',
                asset_type: 'tug',
                asset_name: 'M/V Callie Cate',
                asset_start: '2020-11-15',
                asset_stop: '2020-11-28',
                vendor_name: 'lacarriers',
                start_fuel: '40000',
                stop_fuel: 0,
                start_lube: '200',
                stop_lube: 0,
                created_by: 'Neal White',
                last_modified_by: 'Neal White',
                created_dttm: new Date(),
                modified_dttm: new Date()
              },
              {
              
                asset_id: '3',
                order_id: '2',
                asset_status: 'Active',
                tow_group: '1',
                asset_type: 'barge',
                asset_name: 'CBC 1275',
                asset_start: '2020-11-15',
                asset_stop: '2020-11-28',
                vendor_name: 'canalbarge',
                start_fuel: 0,
                stop_fuel: 0,
                start_lube: 0,
                stop_lube: 0,
                created_by: 'Neal White',
                last_modified_by: 'Neal White',
                created_dttm: new Date(),
                modified_dttm: new Date()
              },
              {
              
                asset_id: '4',
                order_id: '3',
                asset_status: 'Active',
                tow_group: '1',
                asset_type: 'tug',
                asset_name: 'M/V Bilbo Baggins',
                asset_start: '2020-11-15',
                asset_stop: '2020-11-28',
                vendor_name: 'marquette',
                start_fuel: '40000',
                stop_fuel: 0,
                start_lube: '200',
                stop_lube: 0,
                created_by: 'Neal White',
                last_modified_by: 'Neal White',
                created_dttm: new Date(),
                modified_dttm: new Date()
              },
              {
                
                  asset_id: '5',
                  order_id: '3',
                  asset_status: 'Active',
                  tow_group: '2',
                  asset_type: 'tug',
                  asset_name: 'M/V Frodo',
                  asset_start: '2020-11-15',
                  asset_stop: '2020-11-28',
                  vendor_name: 'marquette',
                  start_fuel: '40000',
                  stop_fuel: 0,
                  start_lube: '200',
                  stop_lube: 0,
                  created_by: 'Neal White',
                  last_modified_by: 'Neal White',
                  created_dttm: new Date(),
                  modified_dttm: new Date()
                },
                {
                
                  asset_id: '6',
                  order_id: '3',
                  asset_status: 'Active',
                  tow_group: '2',
                  asset_type: 'barge',
                  asset_name: 'CBC 764',
                  asset_start: '2020-11-15',
                  asset_stop: '2020-11-28',
                  vendor_name: 'canalbarge',
                  start_fuel: 0,
                  stop_fuel: 0,
                  start_lube: 0,
                  stop_lube: 0,
                  created_by: 'Neal White',
                  last_modified_by: 'Neal White',
                  created_dttm: new Date(),
                  modified_dttm: new Date()
                },
                {
              
                    asset_id: '7',
                    order_id: '4',
                    asset_status: 'Active',
                    tow_group: '1',
                    asset_type: 'tug',
                    asset_name: 'M/V JP Boat',
                    asset_start: '2020-11-15',
                    asset_stop: '2020-11-28',
                    vendor_name: 'lacarriers',
                    start_fuel: '40000',
                    stop_fuel: 0,
                    start_lube: '200',
                    stop_lube: 0,
                    created_by: 'Neal White',
                    last_modified_by: 'Neal White',
                    created_dttm: new Date(),
                    modified_dttm: new Date()
                  },
                  {
                    
                      asset_id: '8',
                      order_id: '4',
                      asset_status: 'Active',
                      tow_group: '2',
                      asset_type: 'barge',
                      asset_name: 'CBC 2600',
                      asset_start: '2020-11-15',
                      asset_stop: '2020-11-28',
                      vendor_name: 'canalbarge',
                      start_fuel: 0,
                      stop_fuel: 0,
                      start_lube: 0,
                      stop_lube: 0,
                      created_by: 'Neal White',
                      last_modified_by: 'Neal White',
                      created_dttm: new Date(),
                      modified_dttm: new Date()
                    },
                    {
                    
                      asset_id: '9',
                      order_id: '4',
                      asset_status: 'Active',
                      tow_group: '2',
                      asset_type: 'barge',
                      asset_name: 'CBC 764',
                      asset_start: '2020-11-15',
                      asset_stop: '2020-11-28',
                      vendor_name: 'canalbarge',
                      start_fuel: 0,
                      stop_fuel: 0,
                      start_lube: 0,
                      stop_lube: 0,
                      created_by: 'Neal White',
                      last_modified_by: 'Neal White',
                      created_dttm: new Date(),
                      modified_dttm: new Date()
                    },
                    {
                    
                        asset_id: '10',
                        order_id: '4',
                        asset_status: 'Active',
                        tow_group: '2',
                        asset_type: 'barge',
                        asset_name: 'CBC 760',
                        asset_start: '2020-11-15',
                        asset_stop: '2020-11-28',
                        vendor_name: 'canalbarge',
                        start_fuel: 0,
                        stop_fuel: 0,
                        start_lube: 0,
                        stop_lube: 0,
                        created_by: 'Neal White',
                        last_modified_by: 'Neal White',
                        created_dttm: new Date(),
                        modified_dttm: new Date()
                      }
           ];
        return knex('deckassetfil').insert(assets)
      });
};